name: build-image
on:
  push:
    branches:
      - 'main'
    paths:
      - '.coder/img/**' # only run the action when .coder/img has been modified
  workflow_dispatch:
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v2.1
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/projectname:latest # By default, it will use the repository name as the image name
          context: .coder/img/
          file: .coder/img/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}